### ISSUE TITLE
Credits to Droppers/AnimatedBottomBar

### ISSUE THREAD

**Issue by Droppers** [skydoves/AndroidBottomBar#11]
As people mentioned on your Reddit post (https://www.reddit.com/r/androiddev/comments/htxxfw/a_lightweight_bottom_navigation_view_fully/), you have basically made an identical copy of my library. 

Your library does not add any new features and I fail to understand why you even spend time on making it in the first place. Could you mention my library, since you have clearly used it as your primary inspiration?

https://github.com/Droppers/AnimatedBottomBar

**Comment by skydoves** [comment]
Hi @Droppers,
Thanks for reminding me about the [design credit](https://dribbble.com/shots/6130593-Readable-Tab-Bar) problem. 🙏 

I 100% agree to miss design credits by [Ranjith Manoharan](https://dribbble.com/ranjithmanoharan) on this creation. And also this is my fault that I did not check exactly already there are similar libraries like yours. (It's already late but I found there are some similar libraries if I search the keyword `ReadableBottomBar`). Anyway, sorry for the late action about missing the design license. I just added the [design credits](https://github.com/skydoves/AndroidBottomBar#design-credits) on the bottom of the README.

+) I just want to let you know the truth: I didn't copy from yours, (I didn't know that exists before you mention it), and I appreciate that if you let me know what kinds of codes/points gave that impression to you :)

And I really appreciate that you for reminding this issue again that I've missed. 🙏
Thank you!
