### ISSUE TITLE
Incorrect Indicator x position when navigation is initialised

### ISSUE THREAD

**Issue by dongheeleeme** [skydoves/AndroidBottomBar#8]
Sometimes we can see incorrect location of indicator when navigation is initialised. Is it known issue? If not, Can i assign this issue? @skydoves 😄 

<img src="https://user-images.githubusercontent.com/38916112/98048807-bfcacd00-1e2e-11eb-82b1-467a42adecf4.png" width="300px"/>

**Comment by skydoves** [comment]
I've just assigned this issue to you.
Thanks for creating the issue!

**Comment by dongheeleeme** [comment]
I'll close this issue since this library is not maintained anymore.
